### PR TITLE
fixes #5

### LINKED ISSUE #5: AttributeError: module 'numpy' has no attribute 'float'
Hello,

Thanks for the convenient plugin first!

I installed napari-pystackreg through devbio-napari.
However, when I ran it (Transform), I got the error:
```
AttributeError                            Traceback (most recent call last)
File ~/.pyenv/versions/miniconda3-4.7.12/envs/devbio-napari-env/lib/python3.9/site-packages/superqt/utils/_qthreading.py:617, in create_worker.<locals>.reraise(e=AttributeError("module 'numpy' has no attribute 'float'"))
    616 def reraise(e):
--> 617     raise e
        e = AttributeError("module 'numpy' has no attribute 'float'")

File ~/.pyenv/versions/miniconda3-4.7.12/envs/devbio-napari-env/lib/python3.9/site-packages/superqt/utils/_qthreading.py:178, in WorkerBase.run(self=<napari._qt.qthreading.GeneratorWorker object>)
    176     warnings.filterwarnings("always")
    177     warnings.showwarning = lambda *w: self.warned.emit(w)
--> 178     result = self.work()
        self = <napari._qt.qthreading.GeneratorWorker object at 0x7f77f88489d0>
    179 if isinstance(result, Exception):
    180     if isinstance(result, RuntimeError):
    181         # The Worker object has likely been deleted.
    182         # A deleted wrapped C/C++ object may result in a runtime
    183         # error that will cause segfault if we try to do much other
    184         # than simply notify the user.

File ~/.pyenv/versions/miniconda3-4.7.12/envs/devbio-napari-env/lib/python3.9/site-packages/superqt/utils/_qthreading.py:444, in GeneratorWorker.work(self=<napari._qt.qthreading.GeneratorWorker object>)
    442 try:
    443     _input = self._next_value()
--> 444     output = self._gen.send(_input)
        self = <napari._qt.qthreading.GeneratorWorker object at 0x7f77f88489d0>
        _input = None
        self._gen = <generator object PystackregWidget._run.<locals>._register_stack at 0x7f77f88340b0>
    445     self.yielded.emit(output)
    446 except StopIteration as exc:

File ~/.pyenv/versions/miniconda3-4.7.12/envs/devbio-napari-env/lib/python3.9/site-packages/napari_pystackreg/_widget.py:444, in PystackregWidget._run.<locals>._register_stack(image=<class 'numpy.ndarray'> (5, 201, 199) uint16)
    440 tmats = self.tmats
    442 # transform
--> 444 out = image.copy().astype(np.float)
        image = <class 'numpy.ndarray'> (5, 201, 199) uint16
        np = <module 'numpy' from '/home/hsulab/.pyenv/versions/miniconda3-4.7.12/envs/devbio-napari-env/lib/python3.9/site-packages/numpy/__init__.py'>
    446 self.pbar_label.setText("Transforming...")
    447 yield 0  # reset pbar

File ~/.pyenv/versions/miniconda3-4.7.12/envs/devbio-napari-env/lib/python3.9/site-packages/numpy/__init__.py:284, in __getattr__(attr='float')
    281     from .testing import Tester
    282     return Tester
--> 284 raise AttributeError("module {!r} has no attribute "
        attr = 'float'
        __name__ = 'numpy'
    285                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'float'
```

After searching on the Internet, `pip install "numpy<1.24"` solved the problem!

### PR DESCRIPTION
**Pull request by glichtner**

### CODE REVIEW

**Comment by glichtner** [comment]
Python v3.11.1 tests failing because of https://github.com/napari/napari/pull/5482 (napari bug)
